### ISSUE TITLE
Leak of overflowing log queue

### ISSUE THREAD

**Issue by mdavidsaver** [epics-modules/caPutLog#1]
It looks like there is a missing `caPutLogDataFree()` which would lead to log entries being leaked when the queue is full.

https://github.com/epics-modules/caPutLog/blob/b544f92c6efe1df98506b567f3f7e5137965e2a4/caPutLogApp/caPutLogTask.c#L168-L176

**Comment by anjohnson** [comment]
Ack, thanks.

**Comment by anjohnson** [comment]
Should be fixed by 4a219117023ffc19eb92936c827b648a235971d6
