### ISSUE TITLE
cannot have JSON and non-JSON logger at the same time

### ISSUE THREAD

**Issue by dirk-zimoch** [epics-modules/caPutLog#10]
Because the new JSON logger and the old non-JSON logger are implemented independently but both access the same global resources from caPutLogAs.c, they cannot be used to the same time.

**Comment by anjohnson** [comment]
I don't have any objections to it being possible to use both loggers at the same time, but as I said in #8 we decided that moving to JSON would make it easier to handle the logged data (we wouldn't have to develop a parser for the existing format which wasn't designed with parsing in mind). The APS Upgrade project was willing to fund the JSON development work, and it was easier to implement that as a simple alternative than to work out how to allow both.

**Comment by dirk-zimoch** [comment]
No problem, I was simply having a transition period in mind where people may want to use both loggers at the same time. But if that was never intended, that's fine for me. In that case I need not spend an time on making this use case work.

**Comment by simon-ess** [comment]
Implemented in #15
