### ISSUE TITLE
CAPUT JSON address environment variable listed in documentation is incorrect

### ISSUE THREAD

**Issue by echandler-anl** [epics-modules/caPutLog#24]
The documentation at https://github.com/epics-modules/caPutLog/blob/master/docs/index.rst says to to set EPICS_CA_PUT_JSON_LOG_ADDR, but this variable doesn't work.  You need to set EPICS_CA_JSON_PUT_LOG_ADDR.

**Comment by anjohnson** [comment]
Fixed in commit 3df5287, thanks!
