### ISSUE TITLE
Need new release tag for caPutLog

### ISSUE THREAD

**Issue by bhill-slac** [epics-modules/caPutLog#3]
I've been asked to update our SLAC caPutLog releases to include Andrew's fixes in 2018 and 2019.
Could we get a new R3.7 tag and release for caPutLog?
Our internal process works better if we can base each local release on a collaboration tag.
Besides, others would likely benefit from a new release as well.
Thanks!

**Comment by bfrk** [comment]
I have made a tag and pushed it. Anything else needed? What about tar balls?

**Comment by bfrk** [comment]
Oh, nice, github does that automatically. If R3.7 works for you, please close the ticket.

**Comment by bhill-slac** [comment]
Just what I needed!
Thanks!
